version: '3'
services:
  backend:
    image: balance-bug-backend
    ports:
      - 5000:5000

  frontend:
    image: balance-bug-frontend
    ports:
      - 3000:3000
    depends_on:
      - backend
